name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
    
      - name: Install Serverless v3
        run: npm install -g serverless@3

      - name: Install Dependencies
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to Lambda
        env:
          PORT: ${{ secrets.PORT }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          IS_SERVERLESS: "true"
          MONGO_URL: ${{ secrets.MONGO_URL }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_SECRET: ${{ secrets.EMAIL_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: serverless deploy
